[package]
name = "malware"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version="4.5.26", features = ["derive"]}
windows = { version = "0.59.0", features = [
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_Security",
]}
export-resolver = "1.0.3"